version: '3'

services:
  mysql:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-redmine.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    restart: always
    networks:
      - redmine
      
  redmine:
    image: redmine:latest
    container_name: redmine
    restart: always
    networks:
      - redmine
    volumes:
      - ./redmine-data:/usr/src/redmine/files
    ports:
      - "3001:3000"
    environment:
      REDMINE_DB_MYSQL: mariadb
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine
    depends_on: 
      - mysql

networks:
  redmine:
    driver: bridge