version: "3"
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ./code:/code
            - ./conf:/etc/nginx/conf.d
        ports:
            - "1080:80"
            - "10443:443"
        links:
            - php

    php:
        image: php:7.4-fpm-alpine
        container_name: php
        volumes:
            - ./code:/code
